import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { DiscordIcon } from "@/components/icons";
import Link from "next/link";
import NavLink from "./components/NavLink";
import Image from "next/image";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const servers = [
  { id: "1", img: "/servers/calico.jpeg" },
  { id: "2", img: "/servers/weegie.jpeg" },
  { id: "3", img: "/servers/bengal.jpeg" },
  { id: "4", img: "/servers/siberian.jpeg" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="flex h-screen text-gray-100">
          <div className="space-y-2 overflow-y-scroll bg-gray-900 p-3 ">
            <NavLink href="/">
              <DiscordIcon className="h-5 w-7" />
            </NavLink>
            <hr className="mx-2 rounded border-t-2 border-t-white/[.06]" />
            {servers.map((server) => (
              <NavLink key={server.id} href={`/servers/${server.id}`}>
                <Image
                  src={server.img}
                  alt=""
                  fill={true}
                  className="object-cover"
                />
              </NavLink>
            ))}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
